-- Applied to production:
-- compliance_testing_collection_result_workflow
-- Creates compliance_collection_sites and secure customer RPCs for:
-- testing lifecycle status, collection-site management, and test-result recording.
