-- Applied: compliance_certificates_documents_work_queue
-- Private compliance-documents bucket, document metadata RPC, certificate RPC, work queue RPC, automated deadline/expiration alert refresh, customer audit read policy.
